Feature: bypass install screen and allow custom SECRET_KEY definition
jfelten/gitea-helm-chart pull request #14
Opened 2018-11-08 17:05 UTC by DrMegavolt

@jfelten this is part one: to define custom secret key and skip install step

2018-11-08 17:22 UTC, jfelten commented on templates/gitea/gitea-config.yaml
> +    SECRET_KEY = {{ .Values.config.secretKey }}
Can this be set to a random password if not specified? 
Like this:
{{ if .Values.config.secretKey }}
SECRET_KEY = {{ .Values.config.secretKey }}
{{ else }}
SECRET_KEY = {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}

2018-11-08 17:23 UTC, jfelten commented on values.yaml
> +  secretKey: defaultsecretkeyyouneedtooverride
Comment this out to leave it unset by default
#secretKey: defaultsecretkeyyouneedtooverride

2018-11-08 17:27 UTC, jfelten commented
Please add documentation in README.md for the new values like this:

| `config.secretKey`                    | `gitea` config secretKey                    | `set to a random password`                                                  |

2018-11-08 17:29 UTC, jfelten requested changes
Please see inline comments - when those are addressed LGTM

2018-11-08 21:04 UTC, DrMegavolt commented on templates/gitea/gitea-config.yaml
> +    SECRET_KEY = {{ .Values.config.secretKey }}
I've checked Gitea helper CLI commands. They use 64 random string. 
https://github.com/go-gitea/gitea/blob/master/modules/generate/generate.go#L74 
I did the same

2018-11-08 21:06 UTC, DrMegavolt commented
@jfelten  doc updated; I did the key generation similar to Gitea CLI helper for consistency

2018-11-09 15:12 UTC, jfelten approved these changes
LGTM

2018-11-09 15:12 UTC, merged