fixed port number for external postgres
jfelten/gitea-helm-chart pull request #79
Opened 2020-10-22 14:01 UTC by raducrisan1

The helm chart would fail to install if `useInPodPostgres` is set to `false` and then properly set the `externalDB` fields. This PR fixes the issue.

2020-10-23 03:30 UTC, jfelten requested changes
please bump version

2020-10-23 03:41 UTC, jfelten reviewed
We have been quoting the port in the values file. This is more intuitive, but it might break existing installs. We will allow it but can you add a note in the README.md values table external db port (type int).

2020-10-23 14:40 UTC, jfelten approved these changes
LGTM

2020-10-23 14:53 UTC, merged

2020-10-24 09:01 UTC, raducrisan1 commented
I see the updated chart with version 0.2.8 is not yet available at https://keyporttech.github.io/helm-charts